// <auto-generated />
using DarKnightAndJoker.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DarKnightAndJoker.Server.Migrations
{
    [DbContext(typeof(DarKnightDbContext))]
    [Migration("20240928181008_Primera Migracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DarKnightAndJoker.Server.Models.UsuarioRegistroInicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("emailDark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passworDark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userNameDark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsuariosRegistrosInicios");
                });
#pragma warning restore 612, 618
        }
    }
}
